### ISSUE TITLE
Why are there two conflicting licenses?

### ISSUE THREAD

**Issue by oxygen-dioxide** [lottev1991/LotteV-Voicebank-Update-Repo#1]
The [LICENSE-voicebank](https://github.com/lottev1991/LotteV-Voicebank-Update-Repo/blob/master/LICENSE-voicebank) and [LICENSE-voiceclips](https://github.com/lottev1991/LotteV-Voicebank-Update-Repo/blob/master/LICENSE-voiceclips) in this repo are CC BY 4.0 which says that we are free to redistribute this voicebank and we only need to give appropriate credit. However, after I downloaded the [Chinese voicebank](https://github.com/lottev1991/LotteV-Voicebank-Update-Repo/releases/download/v0.0.1b-hnmu/Hoshino.Hanami.-Ying.Hua-.ZH.CVVC.-FINALE-.BETA.zip), the readme.txt inside it says that we can't redistribute this voicebank.

**Comment by lottev1991** [comment]
That was likely an accident, I'll fix that in due time.

**Comment by oxygen-dioxide** [comment]
So can I redistribute the voicebank now?

**Comment by lottev1991** [comment]
No, that was a mistake, redistribution is not allowed.
